// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as choices from '../../common/choices';

export const household_size: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.size',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:household.size'),
    valueRange: {
        min: 1,
        max: 6
    },
    overMaxAllowed: true,
    conditional: defaultConditional,
    validations: validations.householdSizeValidation
};

export const household_income: WidgetConfig.InputSelectType = {
    ...defaultInputBase.inputSelectBase,
    path: 'household.income',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:household.income'),
    choices: choices.householdIncomeChoices,
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const household_carNumber: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.carNumber',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:household.carNumber'),
    valueRange: {
        min: 0,
        max: 3
    },
    overMaxAllowed: true,
    conditional: defaultConditional,
    validations: validations.carNumberValidation
};

export const home_save: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'home.save',
    label: (t: TFunction) => t('home:home.save')
};
