// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { test } from '@playwright/test';
import * as testHelpers from 'evolution-frontend/tests/ui-testing/testHelpers';
import * as surveyTestHelpers from 'evolution-frontend/tests/ui-testing/surveyTestHelpers';
import { SurveyObjectDetector } from 'evolution-frontend/tests/ui-testing/SurveyObjectDetectors';

const context = {
    page: null as any,
    objectDetector: new SurveyObjectDetector(),
    title: '',
    widgetTestCounters: {}
};

// Modify the CommonTestParameters type with survey parameters
export type CommonTestParametersModify = testHelpers.CommonTestParameters & {
    householdSize: number;
};

// Configure the tests to run in serial mode (one after the other)
test.describe.configure({ mode: 'serial' });

// Initialize the test page and add it to the context
test.beforeAll(async ({ browser }) => {
    context.page = await testHelpers.initializeTestPage(browser, context.objectDetector);
});

/********** Start the survey **********/

// Start the survey with email
surveyTestHelpers.startAndLoginWithEmail({
    context,
    title: '?',
    email: `test${Math.random().toString(36).substring(2, 15)}@test.com`,
    nextPageUrl: '?'
});
// Start the survey without email
surveyTestHelpers.startAndLoginAnonymously({ context, title: '?', hasUser: false });

/********** Tests Home section **********/
export const fillHomeSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the home navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'home', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for home section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'home', completionPercentage: 0 });

    // Test radionumber widget household_size

    // Test select widget household_income with choices householdIncomeChoices
    /* @link file://./../src/survey/common/choices.tsx */

    // Test radionumber widget household_carNumber

    // Test nextbutton widget home_save
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the home navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'home', buttonStatus: 'completed', isDisabled: false });
};

/********** Tests Addresses section **********/
export const fillAddressesSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the addresses navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'addresses', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for addresses section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'addresses', completionPercentage: 0 });

    // Test custom widget addressesInfo
    // Implement custom test

    // Test string widget addressName
    testHelpers.inputStringTest({ context, path: '?.name', value: '?' });

    // Test custom widget addressGeography
    // Implement custom test

    // Test radio widget addressOwnership with choices householdOwnershipChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: '?.ownership', value: '?' });

    // Test number widget addressRent with conditional ifOwnershipTypeIsRentCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.rent', isVisible: true });
    testHelpers.inputStringTest({ context, path: '?.rent', value: '?' });

    // Test radio widget addressAreUtilitiesIncluded with conditional ifOwnershipTypeIsRentCustomConditional with choices yesNo
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.areUtilitiesIncluded', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.areUtilitiesIncluded', value: '?' });

    // Test number widget addressMortgage with conditional ifOwnershipTypeIsBuyCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.mortgage', isVisible: true });
    testHelpers.inputStringTest({ context, path: '?.mortgage', value: '?' });

    // Test custom widget addressInterestRate with conditional ifOwnershipTypeIsBuyCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.interestRate', isVisible: true });
    // Implement custom test

    // Test select widget addressAmortizationPeriod with conditional ifOwnershipTypeIsBuyCustomConditional with choices amortizationYearsCustomChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.amortizationPeriod', isVisible: true });

    // Test number widget addressTaxes with conditional ifOwnershipTypeIsBuyCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.taxes', isVisible: true });
    testHelpers.inputStringTest({ context, path: '?.taxes', value: '?' });

    // Test number widget addressUtilities with conditional askForUtilitiesCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.utilities', isVisible: true });
    testHelpers.inputStringTest({ context, path: '?.utilities', value: '?' });
};

/********** Tests Household section **********/
export const fillHouseholdSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the household navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'household', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for household section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'household', completionPercentage: 0 });

    // Test custom widget householdMembers
    // Widget not active

    // Test number widget personAge
    // Widget not active

    // Test radio widget personDrivingLicenseOwnership with conditional ifAge16OrMoreConditional with choices yesNoDontKnow
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    // Widget not active

    // Test nextbutton widget household_save
    // Widget not active
};

/********** Tests Cars section **********/
export const fillCarsSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the cars navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'cars', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for cars section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'cars', completionPercentage: 0 });

    // Test custom widget carInformation
    // Widget not active

    // Test radio widget carCategory with choices carCategoryChoices
    /* @link file://./../src/survey/common/choices.tsx */
    // Widget not active

    // Test radio widget carEngineType with choices carEngineChoices
    /* @link file://./../src/survey/common/choices.tsx */
    // Widget not active
};
