// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { getAndValidateSurveySections, SurveySectionsConfig } from 'evolution-common/lib/services/questionnaire/types';
import homeConfigs from './sections/home/sectionConfigs';
import addressesConfigs from './sections/addresses/sectionConfigs';
import householdConfigs from './sections/household/sectionConfigs';
import carsConfigs from './sections/cars/sectionConfigs';

// Export all the sections configs
const sectionsConfigs: SurveySectionsConfig = {
    home: homeConfigs,
    addresses: addressesConfigs,
    household: householdConfigs,
    cars: carsConfigs
};
export default getAndValidateSurveySections(sectionsConfigs);
