// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { checkConditionals } from 'evolution-common/lib/services/widgets/conditionals/checkConditionals';
import { type WidgetConditional } from 'evolution-common/lib/services/questionnaire/types';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';

export const ifAge16OrMoreConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 16
            }
        ]
    });
};
