import moment from 'moment';
import i18n from 'evolution-frontend/lib/config/i18n.config';
import { _isBlank } from 'chaire-lib-common/lib/utils/LodashExtensions';
import { getResponse } from 'evolution-common/lib/utils/helpers';
import { countPersons } from 'evolution-common/lib/services/odSurvey/helpers';
import { countCars } from './customHelpers';

// TODO: This custom file should be generated by the Evolution Generator (or eliminated complety).
// TODO: We need this file to setup the interview (language, section start time, actions, household persons count (?)).
// TODO: We also need this file to reject some interviews that are not valid (home not in territory, no adults in household).
// TODO: In other words, if we can improve the Group and Section navigation in Evolution, we can eliminate this file completely.
export default function (interview, sectionShortname) {
    moment.locale(i18n.language); // seems we need this because it is not set correctly globally

    // Prepare the responses object with the household persons count
    const responses = {
        ['response.household._personsCount']: countPersons({ interview }),
        ['response.household._carInfoCount']: countCars({ interview })
    };

    // Check if household size and persons are in sync
    if (sectionShortname !== 'home' && sectionShortname !== 'household') {
        const householdSize = getResponse(interview, 'household.size', undefined);
        const householdPersons = getResponse(interview, 'household.persons', undefined);
        if (!_isBlank(householdSize) && !_isBlank(householdPersons)) {
            const personsCount = responses['response.household._personsCount'];
            if (personsCount !== householdSize) {
                responses['response.household.size'] = personsCount;
            }
        }
    }

    // Check if numbers of cars are in sync
    if (sectionShortname !== 'home' && sectionShortname !== 'household' && sectionShortname !== 'cars') {
        const householdCarNumber = getResponse(interview, 'household.carNumber', undefined);
        const carInformation = getResponse(interview, 'cars', undefined);
        if (!_isBlank(householdCarNumber) && !_isBlank(carInformation)) {
            const carCount = responses['response.household._carInfoCount'];
            if (carCount !== householdCarNumber) {
                responses['response.household.carNumber'] = carCount;
            }
        }
    }
    return responses;
}
