// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as choices from '../../common/choices';
import * as customConditionals from '../../common/customConditionals';
import * as customWidgets from './customWidgets';
import * as customChoices from './customChoices';
import * as customValidations from '../../common/customValidations';

export const addressesInfo = customWidgets.addressesInfo;

export const addressName: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'name',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('addresses:name'),
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const addressGeography = customWidgets.addressGeography;

export const addressOwnership: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'ownership',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('addresses:ownership'),
    choices: choices.householdOwnershipChoices,
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const addressRent: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputNumberBase,
    path: 'rent',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('addresses:rent'),
    conditional: customConditionals.ifOwnershipTypeIsRentCustomConditional,
    validations: validations.requiredValidation
};

export const addressAreUtilitiesIncluded: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'areUtilitiesIncluded',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('addresses:areUtilitiesIncluded'),
    choices: choices.yesNo,
    conditional: customConditionals.ifOwnershipTypeIsRentCustomConditional,
    validations: validations.requiredValidation
};

export const addressMortgage: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputNumberBase,
    path: 'mortgage',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('addresses:mortgage'),
    conditional: customConditionals.ifOwnershipTypeIsBuyCustomConditional,
    validations: validations.requiredValidation
};

export const addressInterestRate = customWidgets.addressInterestRate;

export const addressAmortizationPeriod: WidgetConfig.InputSelectType = {
    ...defaultInputBase.inputSelectBase,
    path: 'amortizationPeriod',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('addresses:amortizationPeriod'),
    choices: customChoices.amortizationYearsCustomChoices,
    conditional: customConditionals.ifOwnershipTypeIsBuyCustomConditional,
    validations: validations.requiredValidation
};

export const addressTaxes: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputNumberBase,
    path: 'taxes',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('addresses:taxes'),
    conditional: customConditionals.ifOwnershipTypeIsBuyCustomConditional,
    validations: validations.requiredValidation
};

export const addressUtilities: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputNumberBase,
    path: 'utilities',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('addresses:utilities'),
    conditional: customConditionals.askForUtilitiesCustomConditional,
    validations: validations.requiredValidation
};
